databases:
  - name: budget_bee_production
    databaseName: budget_bee_production_4x7u
    user: budget_bee_production_4x7u_user

services:
  - type: web
    name: BudgetApp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_bee_production_4x7u
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false