default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin
  host: localhost

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: db/budget_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>